### ISSUE TITLE
Additional Filter Options 

### ISSUE THREAD

**Issue by LeoNerdoG** [eclipse-kapua/kapua#2154]
I have found that additional filter options (listed bellow) should be a good enhancement for a better user experience. Nevertheless I would like opinions from other members regarding this topic. 

**Jobs:**
 - _Target_ filter option (ability to filter Jobs by added targets)
 - _Step_ filter option (ability to filter Jobs by certain "step definition")
 - _Job Description_ dilter option 

**Tags:**
 - _Assigned Devices_ filter option

**Users:**
 - _Credentials_ filter option
 - _Roles_ filter option
 - _Permissions_ filter option

**Roles:** 
 - _Permissions_ filter option 
 - _Granted Users_ filter option
 
**Access Groups:**
 - _Assigned Devices_ filter option

**Testflow:**
1. Login as kapua-sys or any other user that has proper permissions
2. Go to Jobs/Tags/Users/Roles/Access Groups and create an item of every kind (e.g. job1, tag1,...)
3. Observe the filter panels of the mentioned views 

**Expected behavior**
I suggest we add additional filter options (as described above) for user to have more filtering possibilites.

**Screenshots**
/

**Version of Kapua**
1.1.0-SNAPSHOT

**Type of deployment**
[ ] Local Vagrant deployment
[x] Docker
[ ] Openshift (in its variants) 
[ ] Others

**Main component affected**
[x] Console (in case of console please report info on which browser you encountered the problem)
[ ] REST API
[ ] Message Broker
[ ] - Others

Browsers used: 
- Google Chrome (Version 69.0.3497.100 (Official Build) (64-bit))
- Safari (Version 12.0 (13604.3.5))
- Mozilla Firefox (63.0 (64-bit))
- Opera (Version 55.0.2994.44)

**Comment by muros-ct** [comment]
This kind of filters in Kapua is very limited. Grid display supports filtering only on fields that are part of table that contains data for Grid. If field that is filtered on is on table that is referenced from main-grid table over foreign key, Kapua doesn't support this kind of queries and is not possible to simply implement on grid, with paging and sorting support on Grid.

@Coduz and @lorthirk what do you think, shall we close this issue or is sensible implementation possible?
