### ISSUE TITLE
an issue with birth certificate when GPS is on

### ISSUE THREAD

**Issue by ypershin** [eclipse-kapua/kapua#2702]
the DB can't hold 4 digits altitudes

Caused by: org.h2.jdbc.JdbcSQLDataException: Value too long for column "POS_ALTITUDE DECIMAL(11, 8)": "1062.00000000 (12)"; SQL statement:
INSERT INTO dvc_device_event (action, created_on, event_message, received_on, resource, response_code, sent_on, created_by, device_id, id, pos_altitude, pos_heading, pos_latitude, pos_longitude, pos_precision, pos_satellites, pos_speed, pos_status, pos_timestamp, scope_id) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) [22001-199]
at org.h2.message.DbException.getJdbcSQLException(DbException.java:455)
at org.h2.engine.SessionRemote.done(SessionRemote.java:607)
at org.h2.command.CommandRemote.executeUpdate(CommandRemote.java:237)
at org.h2.jdbc.JdbcPreparedStatement.executeUpdateInternal(JdbcPreparedStatement.java:200)
at org.h2.jdbc.JdbcPreparedStatement.executeUpdate(JdbcPreparedStatement.java:154)
at org.eclipse.persistence.internal.databaseaccess.DatabaseAccessor.executeDirectNoSelect(DatabaseAccessor.java:892)

**Comment by Coduz** [comment]
Hi @ypershin 

We have a misconfigured column on the DB which is configured as `DECIMAL(11:8)` which limits the max value to `999.99999999` (max 3 digits before point).

We will change the column definition to `DECIMAL(13:8)` to allow greater values. 
We will also check for other fields that may need some tweaks.

Reference on Gitter: https://gitter.im/eclipse/kapua?at=5d7a63fc46d428101b05d56b

This fix will be also back-ported  on release 1.0.8 

Regards, 

_Alberto_

**Comment by Coduz** [comment]
Hi @ypershin ,

I've made a PR that should solve the problem. If you want you can check if that works for you.

Unfortunately our CI is not picking up the changes and it is not restarting the build, so a bit more time will be required to merge the PR.

Regards, 

_Alberto_

**Comment by ypershin** [comment]
Hi Alberta,
Thank you.  How do I check if that works?

**Comment by ypershin** [comment]
Sorry, Alberto

**Comment by lorthirk** [comment]
You can checkout and build the `fix-gpsInfoColumns` branch (the PR is #2703)

**Comment by ypershin** [comment]
I've deployed kapua-fix-gpsInfoColumns;  still get error message 'Value too long for column "POS_ALTITUDE DECIMAL(11,8)"'

![image](https://user-images.githubusercontent.com/8020305/64965407-2c18f480-d85a-11e9-802a-433a7808bd2d.png)

**Comment by Coduz** [comment]
Uhmmm I'll check on that but the column should have been updated! 
Sorry for that!
I'll try it again tomorrow morning!

**Comment by Coduz** [comment]
Hi @ypershin ,

I've just tested with the containers built from the branch with the fix and I'm able to insert your values in the DB.

![Screen Shot 2019-09-17 at 10 13 42 AM](https://user-images.githubusercontent.com/3942036/65023867-06f8b480-d934-11e9-835c-c6aed98f3986.png)

The only different thing I did was to update directly the database Device Event created. Could you please try to edit your database entry with the value you use from the device to check that is working at DB level?

Thanks, 

_Alberto_

**Comment by ypershin** [comment]
Hi Alberto, 
I finally deployed Kapua with your fix. It works fine.  Thank you.
