### ISSUE TITLE
Job Execution In "Executions" Does Not Finish

### ISSUE THREAD

**Issue by LeoNerdoG** [eclipse-kapua/kapua#2706]
If user starts a job and goes imediatelly to "Executions" tab, the spinning circle icon does not turn into chequered flag (job finished), althoguh job is finished. There should be a certain refresh on this tab? If user changes tab, the "Executions" get refreshed, so there is a workaround it but we should think of a better solution.

**Testflow:**
1. Login as kapua-sys or any other user with proper permissions
2. Connect a live Kura device to Kapua (e.g. device1)
3. Go to Jobs, create a job (e.g. job1)
4. Select job1 and add several steps to it
5. Start the job and go immediatelly to "Executions" tab
6. Observe the job status (there should be a spinning circle by the current execution)

**Expected behavior**
This view should get somehow refreshed so the spinning circle changes to flag icon.

**Screenshot:**
![never_ending_process](https://user-images.githubusercontent.com/15121999/64944223-2a592c00-d86e-11e9-8730-83fbffc23bf6.gif)

**Version of Kapua**
1.1.0-SNAPSHOT

**Type of deployment**
[ ] Local Vagrant deployment
[x] Docker
[ ] Openshift (in its variants) 
[ ] Others

**Main component affected**
[x] Console (in case of console please report info on which browser you encountered the problem)
[ ] REST API
[ ] Message Broker
[ ] - Others

Browsers used: 
- Google Chrome (Version 72.0.3626.119 (Official Build) (64-bit))
- Safari (Version 12.0.3 (14606.4.5))
- Mozilla Firefox (65.0.1 (64-bit))
- Opera (Version:58.0.3135.79)

**Comment by Coduz** [comment]
Hi Leo,

no we do not have auto-refresh on the tabs. 
Do the JobExecutions gets completed if you then refresh the results?

Regards, 

_Alberto_

**Comment by LeoNerdoG** [comment]
Hey,
yes, the tabs get refreshed and everything is ok if tab is refreshed. I know this is a general "problem" with all the views.
I realized just now, that this is actually duplicate of issue #1079 so I am closing this - i had a feeling this issue was posted before but I could not find it.

**Comment by Coduz** [comment]
No problem!
