### ISSUE TITLE
Bug While Creating a New Device From Backend

### ISSUE THREAD

**Issue by zanpizmoht** [eclipse-kapua/kapua#2713]
**Describe the bug**
When creating a device manually from backend there is no checking if the Client Id and/or Display Name contains invalid symbols.

**To Reproduce**
Steps to reproduce the behaviour:
1. In the code, manually create an offline device with name "Dev@123" with create() method from DeviceRegistryServiceImpl.java
2. The device is created, but it should not be as its names contains non permitted symbols.

**Expected behavior**
Kapua should throw KapuaException because special symbols like '@' are not permitted.

**Screenshots**
/

**Version of Kapua**
1.1.0

**Type of deployment**
[ ] Local Vagrant deployment
[ ] Docker
[ ] Openshift (in its variants) 
[x] Others

**Main component affected**
[ ] Console (in case of console please report info on which browser you encountered the problem)
[ ] REST API
[ ] Message Broker
[x] - Others

**Comment by Coduz** [comment]
Hi @zanpizmoht ,

`@` is actually an admitted char. 
I'm working with @riccardomodanese  to check which are the correct rules of validation of that field and we will fix the validation on `DeviceRegistryService`, `DeviceConnectionService` and UI accordingly.

Regards, 

_Alberto_
