### ISSUE TITLE
Impossible starting the job with two "Command Execution" steps

### ISSUE THREAD

**Issue by ct-anaalbic** [eclipse-kapua/kapua#2717]
**Describe the bug**
In test scenario, if user try to add online target/s to the job, and after that two `Command Execution` steps with `Bundle Start` or `Bundle Stop` step between them, starting of the job is impossible. 

**To Reproduce**

1. Login as `kapua-sys` and `kapua-password`
2. Create a job
3. Add one or more online devices as job targets
4. Add `Command Execution` to created job
5. Add several `Bundle Start` and `Bundle Stop` steps to job
6. Add `Command Execution` step again
7. Try to start job

A `JobStartException` was thrown --> `java.lang.IllegalArgumentException`: xJCL invalid per schema. Screenshot is bellow.

**Expected behavior**
Job can be start in every case, with every combination of steps.

**Screenshots**
_Screenshot 1 - Test scenario_ 
![image](https://user-images.githubusercontent.com/45655642/65413790-7d912880-ddf2-11e9-83f0-8eb46a26ea87.png)

_Screenshot 2 - Exception which is thrown_
![image](https://user-images.githubusercontent.com/45655642/65413833-98fc3380-ddf2-11e9-888b-d55a28847237.png)

**Version of Kapua**
[e.g. 1.0.0]

**Type of deployment**
[ ] Local Vagrant deployment
[ ] Docker
[ ] Openshift (in its variants) 
[ ] Others

**Main component affected**
[ ] Console (in case of console please report info on which browser you encountered the problem)
[ ] REST API
[ ] Message Broker
[ ] - Others

**Comment by Coduz** [comment]
I've just tested this and is seems work fine. 
Closing issue

Steps
![Screen Shot 2020-05-05 at 2 02 00 PM](https://user-images.githubusercontent.com/3942036/81063984-218a9880-8ed9-11ea-84bc-a4901c68a5c4.png)

Target
![Screen Shot 2020-05-05 at 2 02 11 PM](https://user-images.githubusercontent.com/3942036/81064002-294a3d00-8ed9-11ea-9bf7-a176629964d9.png)
