### ISSUE TITLE
Unable to store a new Kapua Data Message using Kapua Rest API

### ISSUE THREAD

**Issue by Sravannarra** [eclipse-kapua/kapua#2719]
I'm trying to store a new Kapua Data Message using KapuaRestAPI with the below body 
**BODY:**
{
  "clientId": "virtual",
  "scopeId": "AQ",
  "receivedOn": "2019-09-24T10:01:47.682Z",
  "position": {
    "type": "kapuaPosition",
    "precision": 0,
    "timestamp": "2019-09-24T10:01:47.682Z",
    "status": 0,
    "longitude": 0,
    "latitude": 0,
    "altitude": 0,
    "heading": 0,
    "speed": 0,
    "satellites": 0
  },
  "payload": {
    "type": "kapuaDataPayload",
    "metrics": [
      {
        "name":"temp",
        "value": "29"
      },
       {
        "name":"heat",
        "value": "35"
      }
    ]
  }
}

But I'm getting the following error
**Error:**
{
   "type": "kapuaExceptionInfo",
    "httpErrorCode": 500,
    "message": "An internal error occurred: {0}.",
    "kapuaErrorCode": "INTERNAL_ERROR"
}

Log File Attached, please let me know where I'm doing wrong.
[Container Logs.txt](https://github.com/eclipse/kapua/files/3650883/Container.Logs.txt)

**Comment by lorthirk** [comment]
I see you're missing some parts in your body. Please use this example as a reference:
```
{
  "type": "jsonDatastoreMessage",
  "capturedOn": "2019-09-12T09:25:05.096Z",
  "channel": {
    "type": "kapuaDataChannel",
    "semanticParts": [
      "heater",
      "data"
    ]
  },
  "clientId": "Client-Id-1",
  "deviceId": "WyczTs_GuDM",
  "payload": {
    "metrics": [
      {
        "valueType": "string",
        "value": 5,
        "name": "temperatureExternal"
      },
      {
        "valueType": "string",
        "value": 20,
        "name": "temperatureInternal"
      },
      {
        "valueType": "string",
        "value": 30,
        "name": "temperatureExhaust"
      },
      {
        "valueType": "string",
        "value": 0,
        "name": "errorCode"
      }
    ]
  },
  "receivedOn": "2019-09-12T09:25:05.102Z",
  "sentOn": "2019-09-12T09:25:05.096Z",
  "datastoreId": "bb07d7fc-dc62-492f-b8da-7e28df69e112",
  "timestamp": "2019-09-12T09:25:05.096Z"
}
```

**Comment by Sravannarra** [comment]
Thank you for quick support @lorthirk
