### ISSUE TITLE
move kapua dokcers to another server

### ISSUE THREAD

**Issue by gesaleh** [eclipse-kapua/kapua#2730]
Hi

is it possible and how to move an instance (dockers) that is running on cloud instance to another cloud instance (I don't want to loose the registered devices or job or users)
in fact, the change will be it is new IP (we can change the kapua mqtt IP by dns entry 

thanks

**Comment by Coduz** [comment]
Hi @gesaleh,

I think that this is more a topic for the Docker documentation. 

If you didn't set up the persistence, you'll lose all data stopping the container. The easiest thing would be to make the dump of the databases and restore the dump on the new instances.

Regards, 

_Alberto_

**Comment by Coduz** [comment]
Hi @gesaleh ,

any update on this? 

Regards, 

_Alberto_

**Comment by gesaleh** [comment]
Hi 

this is what I tried to do backup DB but I might did it wrong 
what is the exact procedure of backup/restore 

Thanks

**Comment by Coduz** [comment]
Hi @gesaleh ,

this is H2 database section that you have to follow.

http://www.h2database.com/html/tutorial.html?highlight=backup&search=backup#upgrade_backup_restore

Regards, 

_Alberto_

**Comment by Coduz** [comment]
Hi @gesaleh ,

any update on this? 

Regards, 

_Alberto_
