### ISSUE TITLE
What libraries or frameworks do you recommend to develop an app web that uses the Kapua API?

### ISSUE THREAD

**Issue by cesem589** [eclipse-kapua/kapua#2806]
We are developing an application to use the api of Kapua, which libraries or frameworks do you recommend? angular, react?

**Comment by lorthirk** [comment]
The frontend framework you choose is completely up to you, since you're going to talk with Kapua via REST API anyway.

**Comment by cesem589** [comment]
Thanks for the answer, do you know any demo to guide me?

**Comment by lorthirk** [comment]
You can read REST API documentation currently available at `http://your-kapua-instance.com/doc/`

**Comment by cesem589** [comment]
Thanks and another question, the programming logic where can I put it? If I want to process kapua data, before the app, what aproach can I use for that?

**Comment by lorthirk** [comment]
I guess it all depends on how you want to build your application.

Since the original issue has been answered I'm closing this issue. Please also consider our [Gitter room](https://gitter.im/eclipse/kapua) in order to ask generic questions about the project.
