### ISSUE TITLE
Build failing on Windows machine

### ISSUE THREAD

**Issue by ct-ajovanovic** [eclipse-kapua/kapua#2826]
**Describe the bug**
The build of latest `develop` fails when running `mvn clean install -DskipTests -Pconsole,docker` command on Windows. 
**To Reproduce**
1. Checkout a new branch, up-to-date with the latest `develop`
2. Run `mvn clean install -DskipTests -Pconsole,docker` 
3. The build fails with **The system cannot find the file specified** error in directory `kapua\assembly\api`

**Expected behavior**
The build should pass without errors.

**Screenshots**
_Screenshot 1:_
![image](https://user-images.githubusercontent.com/35954696/72446312-a0858500-37b3-11ea-9e7e-bfe4c8afcd49.png)

_Screenshot 2_
![image](https://user-images.githubusercontent.com/35954696/72446367-ba26cc80-37b3-11ea-8ac6-2d39efcba374.png)

**Version of Kapua**
1.1.0

**Type of deployment**
[ ] Local Vagrant deployment
[X] Docker
[ ] Openshift (in its variants) 
[ ] Others

**Main component affected**
[ ] Console (in case of console please report info on which browser you encountered the problem)
[ ] REST API
[ ] Message Broker
[X] - Others

**Additional context**
Discussion about this error was started on gitter, and as agreed with @lorthirk a new issue is opened.

**Comment by lorthirk** [comment]
This is because apparently `npm install -g swagger-cli` installs the package in different dirs according to the host OS (`target/bin` in MacOS/Linux, `target/node` in Windows).

**Comment by ct-ajovanovic** [comment]
Hi @lorthirk 
As a temporary solution, I tried to change this line here:
https://github.com/eclipse/kapua/blob/8322c752614c03d12f83aa969eeab43e95ae76db/assembly/api/pom.xml#L310
to this:
`<executable>${project.build.directory}/node/swagger-cli</executable>`

But, the build is still not successful after this change and I get these errors:

![image](https://user-images.githubusercontent.com/35954696/72513631-826c6300-384d-11ea-9270-b6e63bac6c54.png)

![image](https://user-images.githubusercontent.com/35954696/72513653-8b5d3480-384d-11ea-9563-be5de4c8a70c.png)

What do you think is causing this error? 
Can some other temporary solution be used here? Until this is fixed?

Regards,
_Aleksandra_

**Comment by lorthirk** [comment]
That's odd, it looks like the NPM package doesn't understand that you're on Windows and then downloads a Unix executable. Maybe it's because you're using a Linux emulation with the Git Shell?

**Comment by ct-ajovanovic** [comment]
Yes, Git Shell does indeed use the Linux bash emulation.
I have run the command in question using Git Bash quite a number of times in the past, and I do not remember ever encountering this error. 
Could this be caused by some recent changes?

**Comment by lorthirk** [comment]
Of course it is. Following #2795, now [swagger-cli](https://www.npmjs.com/package/swagger-cli) is installed and used at build time in order to merge all the OpenAPI specification files in one single file to be served by SwaggerUI. It probably doesn't play that well with your setup, somehow.
