### ISSUE TITLE
Connect a Device without Kura !

### ISSUE THREAD

**Issue by SebsSa** [eclipse-kapua/kapua#2841]
Hey, 
I just started and would like to use Kapua for a project. The project itself already has a communication stack and I would not like to use Kura.

Before I dive into the source code I would like to know if it is possible to connect a device to the Kapua platform in another way?

Unfortunately I can't find any examples or help for this.
Maybe there is someone who can explain to me how to connect a Raspberry Pi as a new device. (without Kura ;) )

**Comment by LeoNerdoG** [comment]
Hey @SebsSa,
I think this question is more suitable for our [Gitter Room](https://gitter.im/eclipse/kapua) - I think you should get answer there fast! =) 

Leo

**Comment by Coduz** [comment]
Discussion continued on Gitter: https://gitter.im/eclipse/kapua?at=5e33ed94f6945f41ef4a43e7
Closing this.
