### ISSUE TITLE
Can't deploy Keycloak as SSO on Openshift

### ISSUE THREAD

**Issue by cbugk** [eclipse-kapua/kapua#2850]
After setting up an X2go-xfce4 enabled server on gcloud, and following procedure below ended up with error: /tmp/builds/dev-tools/openshift/sso/Dockerfile not found

Kapua:  `wget https://github.com/eclipse/kapua/archive/release-1.1.x.zip`
Openshift: 3.11 binaries

Running openshift cluster on Ubuntu18.04 (previously tried Centos7)
`oc cluster up`
`oc login -u system:admin`
`oc adm policy add-cluster-role-to-user cluster-admin admin`

Deploying Kapua   (later on cannot login as system:admin to openshift)
`~/kapua/deployment/openshift/openshift-initialize.sh`
`cd ~/kapua/deployment/openshift`
`./openshift-deploy.sh`
`oc get pods -o wide`  confirms all nodes deployed and running
logged into Kapua console on 172.17.0.20:8080

Deploying Keycloak on openshift
`cd ~/kapua/deployment/openshift/sso`
`oc new-project sso` (was not mentioned on documentation)
in `keycloak-template.yml`, `contextDir: dev-tools/src/main/openshift/sso` -> `contextDir: sso`
in `deploy`, call `env` and `functions` before SMTP checks
then, `./deploy` (providing host, user, password, from(same as user), ssl, port options for yahoo account)

keycloak-build-1-build  STATUS=Init:Error
could not connect github.com (idk why)

on prior trial the error was something like: 

> /tmp/builds/dev-tools/openshift/sso/Dockerfile not found

(Well, I have a substantial docker/docker-compose knowledge, yet not familiar with openshift and kubernetes, let alone kapua and keycloak.)

**Comment by gbarbon** [comment]
Hi @psykobug , just two hints. First of all, concerning  

> could not connect github.com (idk why)

it might be related to the fact it is not able to connect to the github repo (a connection to the kapua github repo is required in order to deploy keycloak on openshift). As for: 

> on prior trial the error was something like:
> 
> /tmp/builds/dev-tools/openshift/sso/Dockerfile not found

The Dockerfile is actually on `deployment/openshift/sso`, not on `dev-tools`. Did you changed something in the project structure, or something that could impact with the way kapua is retrieved from github ?

**Comment by cbugk** [comment]
Firstly, thanks.
Idk why github was not reachable in the first place, but my concern is on the /tmp/... part.

I am curious about whether that file-not-found error was due to pod (container) created having no access to a volume which were to connect `deployment/openshift/sso/`, due to a change in repository's structure (folders being moved around). Where can I check the volumes on keycloak pod (under project "sso")?

Edit: I've made a change in `deployment/openshift/sso/keycloak-template.yml`. Pod was complaining about a file-not-found in `dev-tools/src/main/openshift/sso/`, so updated it to `sso`. On second thought, should've changed into `deployment/openshift/sso` probably. I'll report back.

**Comment by gbarbon** [comment]
I checked the `keycloak-template.yml`, actually the `dev-tools/src/main/openshift/sso/` is pointing to an old position of the sso module. Using `deployment/openshift/sso` as you mentioned should fix it, please keep me updated.

**Comment by cbugk** [comment]
It turns out that, problem of not resolving github.com was due to dns setings of Ubuntu VPS on GCloud. After adding `nameserver 8.8.8.8` (any DNS should suffice) to bottom of `/etc/resolv.conf` and then `oc cluster up`'ing solved it. I guess Centos7 VPS did not have such issue in the first place. Though there are few changes I would like to suggest, I will open requests for those (after I find out how). Kudos @gbarbon 

Source: [Ubuntu /etc/resolv.conf](https://stackoverflow.com/questions/20430371/my-docker-container-has-no-internet/37831194)
