### ISSUE TITLE
Empty Message When Clicking on Devices > Packages > History Button

### ISSUE THREAD

**Issue by LeoNerdoG** [eclipse-kapua/kapua#2869]
If you connect a live Kura device to Kapua and you navigate to Devices > Packages > History, a info box opens that is toraly empty (see screenshot bellow). 

**Testflow:**
1. Login as kapua-sys or any other user that has proper permissions
2. Connect a live Kura device to Kapua and go to Devices > Packages 
3. Click on "History" tab and observe the empty info box on the right hand side

**Expected behavior**
When "History" tab is clicked, nothing should be shown, or there should be something in it.

**Screenshot:**
![Screenshot 2020-02-28 at 08 06 41](https://user-images.githubusercontent.com/15121999/75520054-e6fe0e80-5a04-11ea-9571-9f4641ae576b.png)

**Version of Kapua**
Version 1.1.2

**Type of deployment**
[ ] Local Vagrant deployment
[x] Docker
[ ] Openshift (in its variants) 
[ ] Others

**Main component affected**
[x] Console (in case of console please report info on which browser you encountered the problem)
[ ] REST API
[ ] Message Broker
[ ] - Others

**Browser used:**
Google Chrome (Version 80.0.3987.116 (Official Build) (64-bit))
Mozilla Firefox (Version 73.0 (64-bit))
Opera (Version:66.0.3515.72)
Safari (Version 13.0.5 (15608.5.11))

**Comment by lorthirk** [comment]
Hey @LeoNerdoG,

I was unable to reproduce this. Could you please double check?

**Comment by LeoNerdoG** [comment]
Hey @lorthirk I was unable to reproduce this, so I am closing. Maybe it was a glitch on my side.
