### ISSUE TITLE
Unable to get access to console or other service

### ISSUE THREAD

**Issue by nicomrtnz97** [eclipse-kapua/kapua#2907]
Hello

I have run the docker-deploy.sh on my Rasppberry pi, and then tried to go to de kapua console. I tried with localhost and with the ip address on my rpi browser and in my pc browser but I am no able to enter. 
When I do docker ps -a I get the nex output:
CONTAINER ID       IMAGE                                     STATUS    
8c7fdd07b3d5     "/bin/sh -c /var/opt…"        Exited (1) 46 minutes ago

any idea what is happening?

Thanks

**Comment by LeoNerdoG** [comment]
Hi @uo251410,
Raspberry Pi does not meet the minimum hardware specifications for running Kapua. By this I mean that you don't have at least 8GB of RAM, that is needed to run all the docker containers - you should use a "proper" PC/MAC with at least 8GB of RAM, that should suffice for running you operating system and docker containers. 
I have tried this od all versions of Raspberry Pi (even lastest, version 4) and Kapua cannot run on it. 

Leo

**Comment by Coduz** [comment]
Hi @uo251410 ,

yes I can confirm what @LeoNerdoG said. 
Kapua on docker needs more resources than what a Raspberry Pi can give. You likely will se container that are not running (part or all of them).

Regards, 

_Alberto_

**Comment by lorthirk** [comment]
Since running Kapua on a Raspberry Pi is not supported, I'm closing this issue.
