### ISSUE TITLE
Create Unit Tests for StringUtil Class in Commons Package

### ISSUE THREAD

**Issue by LeoNerdoG** [eclipse-kapua/kapua#2912]
As there is no coverage for StringUtil class in Commons package, I have added some tests to test its functionality - PR will be linked shortly. 

After the PR is merged, this should not be closed, as we will add some more tests.

**Comment by Coduz** [comment]
This has been closed bit GitHub automation. 
I've reopened as per issue description

**Comment by LeoNerdoG** [comment]
I am closing this as the tests for StringUtil have been added with PR #3083.
