### ISSUE TITLE
Cannot connect to child account on Kapua (1.1.3)

### ISSUE THREAD

**Issue by Sin5625** [eclipse-kapua/kapua#2918]
I am using Kura and can connect to Kapua with kapua-sys and kapua-password
However when I make a child account and user, I am not able to connect to it.

[log_27032020.txt](https://github.com/eclipse/kapua/files/4395273/log_27032020.txt)

**Comment by lorthirk** [comment]
Yes, it is a known issue in 1.1.3. Are you sure it's happening in 1.1.2 as well?

**Comment by Sin5625** [comment]
I build 1.1.2 and i can connect. I am changing in the heading.
