### ISSUE TITLE
User Gets Logged Out After 20 Seconds

### ISSUE THREAD

**Issue by LeoNerdoG** [eclipse-kapua/kapua#2931]
I have noticed, that user gets logged out of the console 20 seconds after the login happens - regardless if user clicks something or not. 

**Testflow:**
1. Login as kapua-sys
2. Wait for 20 seconds and then try to click something (e.g. Settings)
3. Observe the error "You are not logged in"

**Expected behavior**
User should not get logged out automatically after 20 seconds. 

**Screenshots**
/

**Version of Kapua**
Latest develop branch

**Type of deployment**
[ ] Local Vagrant deployment
[x] Docker
[ ] Openshift (in its variants) 
[ ] Others

**Main component affected**
[x] Console (in case of console please report info on which browser you encountered the problem)
[ ] REST API
[ ] Message Broker
[ ] - Others

Browsers used:
 - Google Chrome (Version 80.0.3987.163 (Official Build) (64-bit))
 - Mozilla Firefox (74.0.1 (64-bit))

**Comment by lorthirk** [comment]
Do you also have a Kura/ESF console tab open in the same domain, by any chance?

**Comment by LeoNerdoG** [comment]
Yes, I have real Kura device (Raspberry Pi on my home network) and a dockerized Kura available on port 7100 on my local machine - is this a problem?

**Comment by lorthirk** [comment]
I noticed that when you keep both Kapua and Kura tabs, and they both are running on the same domain (e.g. `localhost`), Kapua reports a logout almost immediately. I think there must be come conflict with the Session Cookie or something.

**Comment by LeoNerdoG** [comment]
I would leave this issue open anyway, if anybody else enocunters this or me again 😄 
@lorthirk thanks for your insight and help!

**Comment by craigMull** [comment]
I have recently started playing around with Kapua and kura in docker and can confirm I have seen the same annoying effect, where the user gets logged out of the console a few seconds after the login happens.

After seeing this issue and closing the Kura [docker] Tab, this issue goes away. 

Version of Kapua
Latest develop branch

Type of deployment
[ ] Local Vagrant deployment
[x] Docker
[ ] Openshift (in its variants)
[ ] Others

Main component affected
[x] Console (in case of console please report info on which browser you encountered the problem)
[ ] REST API
[ ] Message Broker
[ ] - Others

Browsers used:

Chromium Version 81.0.4044.138 (Official Build) Built on Ubuntu , running on Ubuntu 18.04 (64-bit)

**Comment by LeoNerdoG** [comment]
I have verified that this issue has been successfully resolved.
