### ISSUE TITLE
Build and test dependencies for Kapua 1.2.0

### ISSUE THREAD

**Issue by stefanomorson** [eclipse-kapua/kapua#2952]
This issue to track build and test dependencies for Kapua 1.2.0:

This CQ has to be filed at least two weeks before submitting the IP log approval:

Name - Version - License

## Maven Plugins:

Maven Exec Plugin (org.codehaus.mojo:exec-maven-plugin) - 1.6.0 - Apache 2.0
https://github.com/mojohaus/exec-maven-plugin
Frontend Maven Plugin (com.github.eirslett:frontend-maven-plugin) - 1.8.0 - Apache 2.0 - 
https://github.com/eirslett/frontend-maven-plugin

## NodeJS Packages

swagger-cli - 4.0.2 - MIT
https://www.npmjs.com/package/swagger-cli

**Comment by lorthirk** [comment]
#2953 fixes the version for `swagger-cli`

**Comment by Coduz** [comment]
CQ filed: [22006](https://dev.eclipse.org/ipzilla/show_bug.cgi?id=22006)

**Comment by Coduz** [comment]
Release has been completed!
