### ISSUE TITLE
Fix getting started on Eclipe Kapua website

### ISSUE THREAD

**Issue by Coduz** [eclipse-kapua/kapua#2968]
**Describe the bug**
We need to update informations on the Eclipse Kapua project website about getting started.

```
$ git clone git@github.com:eclipse/kapua.git kapua
$ cd kapua/deployment/docker
$ ./docker-deploy
```

This need to be fixed and also there is a not available image on the Kura section.

**Comment by lorthirk** [comment]
I fixed the `Getting Started` guide adding Git as a prerequisite, fixing the Unix script path and adding the Windows quickstart. As per the Kura image, it's not on the server anymore, so I removed the reference.
