### ISSUE TITLE
Configuration validation limits string fields to 256 characters

### ISSUE THREAD

**Issue by pintify** [eclipse-kapua/kapua#3002]
**Describe the bug**
In the devices tab, when you are modifying the configuration of a component, the verification of the fields limits the characters of String parameters to 256 as shown in the images:

255 characters ->
![imagen](https://user-images.githubusercontent.com/31854894/84894686-7b1ddf80-b0a1-11ea-94ca-fd43e49d3148.png)

256 characters ->
![imagen](https://user-images.githubusercontent.com/31854894/84894720-87a23800-b0a1-11ea-8919-51e158f65b3b.png)

The error is:
![imagen](https://user-images.githubusercontent.com/31854894/84894741-912ba000-b0a1-11ea-96d8-a6273968991e.png)

And the following message is shown when it is applied (with no success):
![imagen](https://user-images.githubusercontent.com/31854894/84894774-a30d4300-b0a1-11ea-81ab-bcc9d745a95f.png)

In Kura, the field is configured as:

```xml
<AD id="my.property"
   name="Property"
   type="String"
   cardinality="0"
   required="true"
   default="..."
   description="Very interesting property.|TextArea"/>
```

**Version of Kapua**
1.1.0

**Type of deployment**
[ ] Local Vagrant deployment
[x] Docker
[ ] Openshift (in its variants) 
[ ] Others

**Main component affected**
[x] Console (in case of console please report info on which browser you encountered the problem)
[ ] REST API
[ ] Message Broker
[ ] - Others

**Additional context**
The issue seems to be happening also when the same configuration is applied through the batch jobs, but this has not been extensively tested.

The REST API has not been tested

The WireGraph component seems to be working perfectly fine despite of this issue and its field is a string with more than 256 characters

**Comment by Coduz** [comment]
Hi @pintify ,

I'm opening a PR which increases the limit values for fields and textareas.

Regards, 

- Alberto
