### ISSUE TITLE
Account list not properly shown

### ISSUE THREAD

**Issue by pintify** [eclipse-kapua/kapua#3049]
**Describe the bug**
Sometimes (approximately half of the times), when the list of available accounts is shown, it appears with only one row with the kapua-sys account:

![imagen](https://user-images.githubusercontent.com/31854894/89385308-b6cb4200-d6ff-11ea-846b-6d3a111b6842.png)

In these cases, also sometimes the list is just there but only with a one row height view, allowing to choose the account but in a very uncomfortable way.

**To Reproduce**
It is not plenty reproducible as it happens arbitrarily. However, when it happens the steps would be just click on the user and in the Switch to account menu.

**Expected behavior**
The list should appear properly loaded on time, or wait for the data to be properly shown. Another option would be to show a _Loading..._ row while the data is prepared.

**Version of Kapua**
1.2.4

**Type of deployment**
- [ ] Local Vagrant deployment
- [x] Docker
- [ ] Openshift (in its variants) 
- [ ] Others

**Main component affected**
- [x] Console -> Mozilla Firefox
- [ ] REST API
- [ ] Message Broker
- [ ] - Others

**Comment by LeoNerdoG** [comment]
Hey all, I cna confirm the behaviour as I have encountered it. 
I have posted my findings on the relavant PR.

**Comment by Coduz** [comment]
Hi @pintify ,

This has been merged in `develop` and backported in `release-1.2.x` and released with Kapua `1.2.5`.

Regards,

Alberto
