### ISSUE TITLE
Adjustable logging level

### ISSUE THREAD

**Issue by gbarbon** [eclipse-kapua/kapua#3085]
**Is your feature request related to a problem? Please describe.**
The console log level is always set to INFO. It would be nice to allow the user to modify the log level in order to support debugging.

**Describe the solution you'd like**
The Log4j level should be defined through an environment variable.

**Describe alternatives you've considered**
_N/A_

**Additional context**
This is required by the PR #3081 , which enables HTTP requests logging for the SSO module.

**Comment by Coduz** [comment]
This has been closed with #3086
