### ISSUE TITLE
TLS/SSL protocol version selection for MariaDB

### ISSUE THREAD

**Issue by gbarbon** [eclipse-kapua/kapua#3116]
**Is your feature request related to a problem? Please describe.**
We should provide a parameter to force TLS/SSL protocol to a specific set of TLS versions when connecting to Maria DB. This would allow preventing connections using deprecated TLS/SSL versions.

**Describe the solution you'd like**
It should be sufficient to modify the `MariaDBJdbcConnectionUrlResolver` and the `SystemSettingKey` classes to handle this new parameter.

**Describe alternatives you've considered**
_n/a_

**Additional context**
See [here](https://mariadb.com/kb/en/using-tls-ssl-with-mariadb-java-connector/#tls-protocol-version-selection) for more information about the TLS Protocol version selection in MariaDB

**Comment by lorthirk** [comment]
Closed by #3117
