### ISSUE TITLE
Can you please tell me how to run kapua in dev mode locally, for instance I want to make changes in kapua console code and run it on the (jetty or any other) server on localhost in windows/linux os?

### ISSUE THREAD

**Issue by funnyboys1008** [eclipse-kapua/kapua#3118]
We are making our best effort to keep documentation clear and updated.
Unfortunately it can happen that we have failed. 
Feel free to submit your question about Kapua. Please try to use the search box to search across open/closed issue before submitting a new question: you may be not the first with that question!

**Comment by lorthirk** [comment]
Hi @funnyboys1008 !

Am I correct assuming that you're working on update the Kapua documenation? If so, it would be great if you could contribute it to the community!

**Comment by funnyboys1008** [comment]
> Hi @funnyboys1008 !
> 
> Am I correct assuming that you're working on update the Kapua documenation? If so, it would be great if you could contribute it to the community!

Yes, surely I will update the kapua documentation as well.

**Comment by lorthirk** [comment]
That's great.

I'm not sure what you're asking here in this issue though 😄

**Comment by funnyboys1008** [comment]
> That's great.
> 
> I'm not sure what you're asking here in this issue though 😄


Hi, I am asking if I want to add something in the kapua-console UI (a tab or something) so I want to run kapua console on localhost for dev purpose on eclipse on ubuntu machine for quick changes, how can set it up?

**Comment by lorthirk** [comment]
Sorry for the late answer.

Unfortunately, in this moment the Console is a bit of a pain to setup for development: you would need a GWT plugin in your IDE (I use IntelliJ Professional that has GWT support enabled by default), and also a Firefox extension that will not run on Firefox versions older than 26 to debug the client side code. Apart from this, it's a common Web Application, so you should be able to configure it as such in Tomcat or Jetty.
