### ISSUE TITLE
external/pom.xml not found

### ISSUE THREAD

**Issue by teamrdwitti** [eclipse-kapua/kapua#3196]
Dear all,

I'm trying to build Kapua from scratch as described in the developer's guide.
The first instruction  mvn clean install -f external/pom.xml failed as the file external/pom.xml does not exist.

I had a look at earlier versions without finding it.

I played with Maven some years ago, and I'm quite puzzled.

Many thanks for your help,

**1.4.0**

**Type of deployment**
[ ] Local Vagrant deployment
[X] Docker
[ ] Openshift (in its variants) 
[ ] Others

**Main component affected**
[ ] Console (in case of console please report info on which browser you encountered the problem)
[ ] REST API
[ ] Message Broker
[ ] - Others

**Additional context**

**Comment by LeoNerdoG** [comment]
Hey @teamrdwitti,
you should just execute the following commands (you have to have Docker Desktop installed and running):
1. mvn clean install -DskipTests -Pdocker (in Kapua root folder)
2. go to /deployment/docker/unix (if you have Linux/MAC machine)
3. Run command ./docker-deploy.sh
4. Afterwards Kapua should be accesible on localhost:8080

If you need any more information, please let us know. 
Leo

**Comment by Coduz** [comment]
Hi @teamrdwitti ,

there is an error on the documentation and that step is no longer necessary. 
I'll fix the documentation. 

Regards, 

_Alberto_
