### ISSUE TITLE
Possible issue with class DataStoreMetrics.java

### ISSUE THREAD

**Issue by sonja-ct** [eclipse-kapua/kapua#3206]
**Describe the bug**
In class DataStoreMetrics.java from broker/core/listener package two constant variables have the same values.

    public static final String METRIC_MODULE_NAME = "datastore";
    public static final String METRIC_COMPONENT_NAME = "datastore";

**Screenshots**
/

**Version of Kapua**
latest develop branch

**Additional context**
/

**Comment by Coduz** [comment]
Hi @sonja-ct 

that is correct because one is the module name and one is the component name.
For now `datastore` module has only one component but there can been others.

So this is ok.

Regards, 

_Alberto_
