### ISSUE TITLE
Deployment script is failing for missing docker image kapua/kapua-job-engine on docker hub.

### ISSUE THREAD

**Issue by pravin-raha** [eclipse-kapua/kapua#3263]
**Describe the bug**
I have followed installation document. But `./docker-deploy.sh` script is failing because it can't pull  `kapua/kapua-job-engine ` docker image.
I checked docker hub, but there is no public docker image of `kapua-job-engine`.

**Expected behavior**
Should pull docker image from docker hub.

**Type of deployment**
Docker

**Comment by LeoNerdoG** [comment]
This is a duplicate of #3262. 

@pravin-raha, please follow these steps:
1. Run command mvn clean install -DskipTests -Pconsole,docker (this will build the docker images locally, which also includes kapua-job-engine)
2. Run the ./docker-deploy.sh script 

This should solve your problem and yes, you are right about the kapua-job-engine image not being in Docker Hub - the development team did not yet upload it there. Once it is uploaded, users will be able to deploy kapua without building it locally.

**Comment by pravin-raha** [comment]
Ok, Thanks
