### ISSUE TITLE
Update the MFA POST REST API Swagger example

### ISSUE THREAD

**Issue by gbarbon** [eclipse-kapua/kapua#3281]
**Describe the bug**
The POST `/{scopeId}/users/{userId}/mfa` Swagger example of the MFA REST API should be updated, since it is not showing the QR code base64 image and the scratch codes.

**To Reproduce**
Deploy Kapua and open the Swagger endpoint from a browser.

**Expected behavior**
The Swagger example should contain the QR code base64 image and the scratch codes.

**Screenshots**
_n/a_

**Version of Kapua**
1.5.0-SNAPSHOT

**Type of deployment**
[ ] Local Vagrant deployment
[ ] Docker
[ ] Openshift (in its variants) 
[x] Others

**Main component affected**
[ ] Console (in case of console please report info on which browser you encountered the problem)
[x] REST API
[ ] Message Broker
[ ] - Others

**Additional context**
_n/a_

**Comment by Coduz** [comment]
This issue has been resolve a long time ago by https://github.com/eclipse/kapua/pull/3960
