### ISSUE TITLE
Unable to update user via Rest API

### ISSUE THREAD

**Issue by dusanp795** [eclipse-kapua/kapua#3290]
**Describe the bug**
It is not possible to edit the user using the Rest API, because the edit Username option is disabled on the UI.

1. Deploy Kapua
2. Open Swagger 
3. Authenticate with the user
4. Update an existing user via PUT request

**Expected behavior**
End user should be able to edit specific user information via REST api. 

**Screenshots**
![Screenshot from 2021-04-02 15-02-05](https://user-images.githubusercontent.com/81570342/113673797-b4b7e980-96b9-11eb-99d5-1aea46b46d26.png)

**Version of Kapua**
latest develop

**Type of deployment**
[ ] Local Vagrant deployment
[x] Docker
[ ] Openshift (in its variants) 
[ ] Others

**Main component affected**
[ ] Console (in case of console please report info on which browser you encountered the problem)
[x] REST API
[ ] Message Broker
[ ] - Others

**Additional context**
Should the behavior be like the UI (disable edit username) or should it be like the Rest API (enable edit username)?

**Comment by lorthirk** [comment]
The error shows you're sending a wrong `optmisitc_lock` value, so you want to read the current value first since it has been update since your last read.

**Comment by dusanp795** [comment]
You were right. Close issue by my mistake.
