### ISSUE TITLE
Unable to perform user authorization via Swagger

### ISSUE THREAD

**Issue by dusanp795** [eclipse-kapua/kapua#3305]
**Describe the bug**
The POST request for / authentication / user  on Swagger doesn't pass.

**To Reproduce**
1. Deploy Kapua
2. Open Swagger
3. Select POST request for / authentication / user and execute it

**Expected behavior**
The end user should be to receive responses from the server, with status code 200 (JSON), which contains the tokenId required for Authorization.

**Screenshots**
![Screenshot](https://user-images.githubusercontent.com/81570342/117127555-843c9b80-ad9c-11eb-8e56-943903509ee0.png)
![Screenshot 2](https://user-images.githubusercontent.com/81570342/117127563-87378c00-ad9c-11eb-9a80-b6f8d0e366a6.png)

**Version of Kapua**
latest develop

**Type of deployment**
[ ] Local Vagrant deployment
[x] Docker
[ ] Openshift (in its variants) 
[ ] Others

**Main component affected**
[ ] Console (in case of console please report info on which browser you encountered the problem)
[x] REST API
[ ] Message Broker
[ ] - Others

**Additional context**
/

**Comment by lorthirk** [comment]
Have you enabled the CORS Origin in the Console Settings?

More info #3278

**Comment by dusanp795** [comment]
I add a new CORS with the path: "http: // localhost: 8081". And now I got a response to the POST request. Is that right?

**Comment by lorthirk** [comment]
I think it is?

I mean, is the response the one you expect?

**Comment by dusanp795** [comment]
Response is correct, as I expect. You were right. Closed issue.

**Comment by dusanp795** [comment]
Response is correct, as I expect. You were right. Closed issue.
