### ISSUE TITLE
./deployment/docker/unix/docker-deploy.sh fails - kapua/kapua-job-engine image does not exist

### ISSUE THREAD

**Issue by kjones-kore** [eclipse-kapua/kapua#3312]
**Describe the bug**
Demo setup fails. job-engine docker image does not exist when attempting to download docker images for demo setup. No such image kapua/job-engine exists.

**To Reproduce**
1. Run from user home directory
2. `git clone https://github.com/eclipse/kapua`
2. `cd kapua`
3. `./deployment/docker/unix/docker-deploy.sh`
4. docker-compose pulls images up to and including kapua/kapua-api
5. Receive installation messages:

Status: Downloaded newer image for kapua/kapua-api:latest
Pulling job-engine (kapua/kapua-job-engine:latest)...

6. Receive error messages:
ERROR: The image for the service you're trying to recreate has been removed. If you continue, volume data could be lost. Consider backing up your data before continuing.
Continue with the new image? [yN]
ERROR: pull access denied for kapua/kapua-job-engine, repository does not exist or may require 'docker login': denied: requested access to the resource is denied

**Expected behavior**
Image should be available to satisfy the docker-compose.yml configuration file

**Screenshots**
n/a

**Version of Kapua**
1.4.4

**Type of deployment**
[ ] Local Vagrant deployment
[ X] Docker
[ ] Openshift (in its variants) 
[ ] Others

**Main component affected**
[ ] Console (in case of console please report info on which browser you encountered the problem)
[ ] REST API
[ ] Message Broker
[ ] - Others - job-engine image missing

**Additional context**
Running Ubuntu 20.04.2 (Focal)
Running docker 20.10.5, build 55c4c88

**Comment by mehdidjait** [comment]
I had the exact same problem using docker-deploy.ps1 running Windows. 

I have zero experience with docker (and kapua btw.), but looking here https://hub.docker.com/u/kapua 
Indeed, kapua-job-engine does not exist.

So I went to kapua\deployment\docker\compose\docker-compose.yml and removed kapua-job-engine.
I have now access to the kapua console.

**Comment by lorthirk** [comment]
Have a look at the the [Developer Guide-->Docker Images](https://github.com/eclipse/kapua/blob/a19266371b8113b384deebe11155e66170569bf7/docs/developer-guide/en/building.md#docker-images)

You need to build the Kapua Docker Images from sources if you launch `./docker-deploy` from the `develop` branch. Either build them, or switch to a released tag before deploying.
