### ISSUE TITLE
When attribute invalidated_on has not null value,  can't find data by tokenId.

### ISSUE THREAD

**Issue by miricy** [eclipse-kapua/kapua#3317]
**Describe the bug**
source path:
[service/security/shiro/src/main/java/org/eclipse/kapua/service/authentication/shiro/AuthenticationServiceShiroImpl.java](https://github.com/eclipse/kapua/blob/develop/service/security/shiro/src/main/java/org/eclipse/kapua/service/authentication/shiro/AuthenticationServiceShiroImpl.java)
In this class the function 'findAccessToken' and 'findRefreshableAccessToken' has below code line:
 **accessTokenQuery.attributePredicate(AccessTokenAttributes.INVALIDATED_ON, null, Operator.IS_NULL)**

When attribute invalidated_on has not null value,  can't find data by tokenId.

**Version of Kapua**
[e.g. 1.5.0-SNAPSHOT]

**Comment by lorthirk** [comment]
This is by design, since a token that has a non null `invalidated_on` it's not valid anymore, and that method is intended to search for valid tokens. You can perform your own query using the `AccessTokenService.query()` method.

**Comment by miricy** [comment]
rest-api/resources/src/main/java/org/eclipse/kapua/app/api/resources/v1/resources/Authentication.java 
The refresh api not working properly
```
@POST    
@Consumes({MediaType.APPLICATION_JSON, MediaType.APPLICATION_XML})    
@Produces({MediaType.APPLICATION_JSON, MediaType.APPLICATION_XML})    
@Path("refresh")    
public AccessToken refresh(RefreshTokenCredentials refreshTokenCredentials)
 throws KapuaException {        
   return authenticationService.refreshAccessToken(refreshTokenCredentials.getTokenId(),refreshTokenCredentials.getRefreshToken());   
 }
```
It seems I can't refresh the token by tokenid , because the 'invalidated_on' is not null when it's created.

**Comment by lorthirk** [comment]
Ok, this is a valid point, although I am a bit concerned about the performances when there are a lot of Access Tokens in the table. In my experience, that table can grow up to hundreds of thousands of rows pretty quickly.

@Coduz any thoughs?

**Comment by miricy** [comment]
Yes, it may need to add a method to automatically clear expired  Access Tokens, or use cache tools Set automatically clear time

**Comment by lorthirk** [comment]
I was reasoning about this, and I realized something I missed out in the first place: if a token has not null `invalidated_on`, it means it has been either already refreshed or explicitly invalidated. In both cases you should not refresh it again, so the behaviour is correct. If you're trying to do a second refresh after you already made one, please note that after the first refresh you will obtain a new token, which is different from the one you refreshed. So it's this new token you have to refresh now.

**Comment by miricy** [comment]
After refreshing, the database does not add new records, but only updates the new token. Through the new token, the database record can be updated again, so that the refreshing will not produce new database records, and the application can refresh before the token expires， Should be refreshable before invalid time.

**Comment by lorthirk** [comment]
I'm sorry, I don't think I understand your last comment.

Refreshing an Access Token (I know, probably it's a bad wording) actually creates an entire new session with a new access token, and invalidates the old one. So yes, a new Access Token should appear in the DB. Are you saying that this is not what you're observing?

**Comment by miricy** [comment]
Thank you for your reply.
Maybe I didn't describe it clearly。Use the new session, new tokenId,The new token cannot be refreshed in any case. 
In fact, in order to keep the client in the login state, the app needs to be refreshed the token regularly，To keep it from expiration，

**Comment by lorthirk** [comment]
Yes, but you always do that in the LAST token. I mean: you login, and you get the token `fooToken`. Before the Refresh period expires (the date in the `refresh_expires_on` field), you can issue a `/authentication/refresh` with the refresh token (the one that is a GUID). When you do that (or when you call `/authentication/logout` with that token, and **only in these two cases**, the `invalidated_on` field gets populated with the current date and time, and you receive **a new access token** (let's say `barToken`), with its own refresh token. From now on, all your operations need to be carried out with this new access token, **including the next refresh**, when you will get a new access token once more (`bazToken`), and the previous one will be invalidated. And so on.

So, if you're telling me that you cannot refresh the second access token with its own refresh token, then this may be the issue we should investigate.

**Comment by miricy** [comment]
Yes, I cannot refresh the second access token with its own refresh token.

**Comment by lorthirk** [comment]
Ok. Would you mind closing this issue and create a new one, then?
