### ISSUE TITLE
Building and Running kapua on Ubuntu 20.04 with (Fail while making docker images)

### ISSUE THREAD

**Issue by rezahili** [eclipse-kapua/kapua#3325]
Hello, hope you're doing well.
I tried to build and Run Kapua on ubuntu 20.04 amd64bit.
They are my steps and errors: 
1-JDK8
`sudo apt-get install openjdk-8-jdk`
2- mvn
`sudo apt install maven`
3- [docker](https://docs.docker.com/engine/install/ubuntu/) and docker [compose](https://docs.docker.com/compose/install/)
4- `git clone https://github.com/eclipse/kapua.git kapua`
5- `cd kapua`
6- `sudo su`
7- `mvn clean install`
And then I've got this error that is related to kapua-security-shiro:

[ERROR] Failures:
[ERROR]   AuthenticationUtilsTest.cryptCredentialSHAAlgorithmTest:74->Assert.assertEquals:645->Assert.failNotEquals:834->Assert.fail:88 Expected and actual values should be the same. expected:<77> but was:<141>
[ERROR]   AuthenticationUtilsTest.decryptAesEmptyKeyTest Expected exception: java.lang.IllegalArgumentException
[ERROR]   AuthenticationUtilsTest.decryptAesIncorrectKeyTest Expected exception: org.eclipse.kapua.KapuaRuntimeException
[ERROR]   AuthenticationUtilsTest.encryptAesEmptyKeyTest Expected exception: java.lang.IllegalArgumentException
[ERROR]   AuthenticationUtilsTest.encryptAesIncorrectKeyTest Expected exception: org.eclipse.kapua.KapuaRuntimeException
[INFO]
[ERROR] Tests run: 472, Failures: 5, Errors: 0, Skipped: 0
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for kapua 1.5.0-SNAPSHOT:
[INFO]
[INFO] kapua-build-tools .................................. SUCCESS [  1.724 s]
[INFO] kapua .............................................. SUCCESS [ 25.008 s]
[INFO] kapua-qa ........................................... SUCCESS [  1.998 s]
[INFO] kapua-qa-markers ................................... SUCCESS [  1.958 s]
.
.
.
.
[INFO] kapua-security-registration ........................ SUCCESS [  0.200 s]
[INFO] kapua-security-registration-api .................... SUCCESS [  0.313 s]
[INFO] kapua-security-certificate ......................... SUCCESS [  0.302 s]
[INFO] kapua-security-certificate-api ..................... SUCCESS [  0.293 s]
[INFO] kapua-security-shiro ............................... FAILURE [01:10 min]
[INFO] kapua-datastore .................................... SKIPPED
[INFO] kapua-datastore-api ................................ SKIPPED
[INFO] kapua-message-internal ............................. SKIPPED
[INFO] kapua-datastore-internal ........................... SKIPPED
[INFO] kapua-transport .................................... SKIPPED
.
.
.
.
[INFO] kapua-docker ....................................... SKIPPED
[INFO] kapua-minishift .................................... SKIPPED
[INFO] kapua-openshift .................................... SKIPPED
[INFO] kapua-deployment-commons ........................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  03:10 min
[INFO] Finished at: 2021-06-03T14:25:24+02:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.20:test (default-test) on project kapua-security-shiro: There are test failures.
[ERROR]
[ERROR] Please refer to /root/kapua/service/security/shiro/target/surefire-reports for the individual test results.
[ERROR] Please refer to dump files (if any exist) [date]-jvmRun[N].dump, [date].dumpstream and [date]-jvmRun[N].dumpstream.
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <args> -rf :kapua-security-shiro

                                End OF ERROR

     Next, I tried to make my local images so I ran this :
     `mvn -f assembly -Pdocker`
     
    Then I got this error:
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for kapua-assembly 1.5.0-SNAPSHOT:
[INFO]
[INFO] kapua-assembly ..................................... SUCCESS [  4.081 s]
[INFO] kapua-assembly-java-base ........................... SUCCESS [  4.259 s]
[INFO] kapua-assembly-jetty-base .......................... SUCCESS [  1.285 s]
[INFO] kapua-assembly-sql ................................. SUCCESS [  0.451 s]
[INFO] kapua-assembly-events-broker ....................... SUCCESS [  0.593 s]
[INFO] kapua-assembly-broker .............................. FAILURE [  1.734 s]
[INFO] kapua-assembly-api ................................. SKIPPED
[INFO] kapua-assembly-job-engine .......................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  13.167 s
[INFO] Finished at: 2021-06-03T14:38:42+02:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project kapua-assembly-broker: Could not resolve dependencies for project org.eclipse.kapua:kapua-assembly-broker:pom:1.5.0-SNAPSHOT: The following artifacts could not be resolved: org.eclipse.kapua:kapua-broker-core:jar:1.5.0-SNAPSHOT, org.eclipse.kapua:kapua-message-internal:jar:1.5.0-SNAPSHOT, org.eclipse.kapua:kapua-datastore-internal:jar:1.5.0-SNAPSHOT, org.eclipse.kapua:kapua-security-shiro:jar:1.5.0-SNAPSHOT, org.eclipse.kapua:kapua-device-call-kura:jar:1.5.0-SNAPSHOT, org.eclipse.kapua:kapua-device-management-api:jar:1.5.0-SNAPSHOT, org.eclipse.kapua:kapua-device-management-job-api:jar:1.5.0-SNAPSHOT, org.eclipse.kapua:kapua-device-management-job-internal:jar:1.5.0-SNAPSHOT, org.eclipse.kapua:kapua-device-registry-internal:jar:1.5.0-SNAPSHOT, org.eclipse.kapua:kapua-device-management-registry-api:jar:1.5.0-SNAPSHOT, org.eclipse.kapua:kapua-device-management-registry-internal:jar:1.5.0-SNAPSHOT, org.eclipse.kapua:kapua-job-internal:jar:1.5.0-SNAPSHOT, org.eclipse.kapua:kapua-job-engine-api:jar:1.5.0-SNAPSHOT, org.eclipse.kapua:kapua-job-engine-client:jar:1.5.0-SNAPSHOT, org.eclipse.kapua:kapua-scheduler-api:jar:1.5.0-SNAPSHOT, org.eclipse.kapua:kapua-scheduler-quartz:jar:1.5.0-SNAPSHOT, org.eclipse.kapua:kapua-security-certificate-internal:jar:1.5.0-SNAPSHOT, org.eclipse.kapua:kapua-tag-api:jar:1.5.0-SNAPSHOT, org.eclipse.kapua:kapua-tag-internal:jar:1.5.0-SNAPSHOT, org.eclipse.kapua:kapua-user-internal:jar:1.5.0-SNAPSHOT, org.eclipse.kapua:kapua-rest-api-core:jar:1.5.0-SNAPSHOT, org.eclipse.kapua:kapua-translator-kapua-kura:jar:1.5.0-SNAPSHOT, org.eclipse.kapua:kapua-translator-kura-jms:jar:1.5.0-SNAPSHOT, org.eclipse.kapua:kapua-translator-kura-mqtt:jar:1.5.0-SNAPSHOT, org.eclipse.kapua:kapua-transport-api:jar:1.5.0-SNAPSHOT, org.eclipse.kapua:kapua-transport-jms:jar:1.5.0-SNAPSHOT, org.eclipse.kapua:kapua-transport-mqtt:jar:1.5.0-SNAPSHOT: Could not find artifact org.eclipse.kapua:kapua-broker-core:jar:1.5.0-SNAPSHOT -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <args> -rf :kapua-assembly-broker

**Comment by rezahili** [comment]
The problem probably was a new type of SHA algorithms in ubuntu20.04.(According to @lorthirk ).
The only thing that I've done to fix this was by adding `-DskipTests` to the end of  this command(append ): `mvn clean install`
I mean this `mvn clean install -DskipTests`
Actually, I've skipped those tests which were not crucial while Building.

**Comment by rezahili** [comment]
Another thing I have to mention is we need at least 8 GiG RAM on the server or anything we want to use as a Kapua cloud.

**Comment by lorthirk** [comment]
> The problem was a new type of SHA algorithms in ubuntu20.04.(According to @lorthirk ).

Well, that's not exactly what I said ([here](https://gitter.im/eclipse/kapua?at=60b8cf98fec22b4786f865f2)): I'm honestly not sure about the cause, an investigation would be needed but I have no Ubuntu 20.04 system available right now.

> Another thing I have to mention is we need at least 8 GiG RAM on the server or anything we want to use as a Kapua cloud.

Yes, this is due to Elasticsearch requiring most of that 8Gi of RAM. Be advised that running Kapua with a containerized Elasticsearch (and thus the Docker Compose deployment) is only recommended for development purposes, and not for production.

**Comment by rezahili** [comment]
> > The problem was a new type of SHA algorithms in ubuntu20.04.(According to @lorthirk ).
> 
> Well, that's not exactly what I said ([here](https://gitter.im/eclipse/kapua?at=60b8cf98fec22b4786f865f2)): I'm honestly not sure about the cause, an investigation would be needed but I have no Ubuntu 20.04 system available right now.
> 
> > Another thing I have to mention is we need at least 8 GiG RAM on the server or anything we want to use as a Kapua cloud.
> 
Yes, exactly I added "probably" into my sentence, and sorry for that.

> 

> Yes, this is due to Elasticsearch requiring most of that 8Gi of RAM. Be advised that running Kapua with a containerized Elasticsearch (and thus the Docker Compose deployment) is only recommended for development purposes, and not for production.

So, which type of running is better for production purposes?

**Comment by lorthirk** [comment]
> So, which type of running is better for production purposes?

It depends mostly on your use case, your expected traffic and a number of other factors. For sure I would look for a dedicated ES cluster, somewhere down the line, and a separate SQL database as well. But it really depends on what you have in mind.

**Comment by rezahili** [comment]
> > So, which type of running is better for production purposes?
> 
> It depends mostly on your use case, your expected traffic, and a number of other factors. For sure I would look for a dedicated ES cluster, somewhere down the line, and a separate SQL database as well. But it really depends on what you have in mind.

I think we will add 1000 devices every year. we're going to start with 50 to 100 devices, so our scale is not millions.
. Maybe we want to use one type of NoSQL database(in next coming years we will have BigData too). And about traffic, we want to gather when the device gets online perfectly(so we have local storage) and there is no high traffic in real-time. What is your Idea?

**Comment by lorthirk** [comment]
Honestly, there's nothing you could tell me that would be enough to give you a proper suggestion. There are too many variables. It's something definitely up to you to properly assess your use case.
