### ISSUE TITLE
kapua and kura mqtt connection fail( kapua dosn't show my connected kura device on devices tab on kapua web-console and also I cant send messege )

### ISSUE THREAD

**Issue by rezahili** [eclipse-kapua/kapua#3327]
Hi, hope everything is going well with you.
I installed Kapua on my cloud as a server and Kura on another server as a device. I used [this document](https://github.com/eclipse/kapua/pull/780/files) and connected to Kapua successfully as I can see in the connections tab on Kapua([look at this](https://pasteboard.co/K56TNKyq.png)) and then I found out that, there is no device on the devices tab of Kapua([ look at this one](https://pasteboard.co/K56ZF7U.png)). I couldn't make communication (sending a message using MQTT and receive it on the database)and I don't know what is happening...( I don't know if this is a bad configuration or BUG) 
[this is my Kura configuration](https://pasteboard.co/K56WYYH.png) according to [this document](https://github.com/eclipse/kapua/pull/780/files).
 Thank U.

**Comment by lorthirk** [comment]
Are you connecting on the root Kapua account (kapua-sys) or a child account? If the latter, did you assign a minimum Devices limit to that account?

**Comment by rezahili** [comment]
> Are you connecting on the root Kapua account (Kapua-sys) or a child account? If the latter, did you assign a minimum Devices limit to that account?

Yes. I created a child account and then I went to the Account settings of that child account and set all of them to true(except  TagService) and yes I did assign DeviceRegistryService to 10. But I still can't see my device.

**Comment by lorthirk** [comment]
Can you check the Broker's container logs?

**Comment by rezahili** [comment]
> Can you check the Broker's container logs?

I deleted accounts and set accounts again and it works(Now I can see my Device). but I still couldn't send a message using [this plugin](https://marketplace.eclipse.org/content/example-publisher-eclipse-kura-4xy) and get it in the database!!

**Comment by rezahili** [comment]
> > Can you check the Broker's container logs?
> 
> I deleted accounts and set accounts again and it works(Now I can see my Device). but I still couldn't send a message using [this plugin](https://marketplace.eclipse.org/content/example-publisher-eclipse-kura-4xy) and get it in the database!!

I used [anotherone](https://marketplace.eclipse.org/content/example-publisher-eclipse-kura-3xy) and it works.
