### ISSUE TITLE
fail to configure files for MQTTS(SSL) communication between Kapua and Kura ( this directory: /var/opt/activemq was not exist after changing files for having ssl)

### ISSUE THREAD

**Issue by rezahili** [eclipse-kapua/kapua#3328]
Hello again, wish you nothing but the best.
So, after working on communication between Kura and Kapua, Now I'm trying to use SSL and there are some problems.

 
They are my steps and now:
1- docker-undeploy.sh 
2- Acroding to @lorthirk [commit on Oct 2, 2018 ](https://github.com/eclipse/kapua/pull/2054/files) I changed files.
3- ./docker-deploy
4- I supposed to have a directory like var/opt/activemq and find my certificate file after deploying, but I couldn't.

Due to this part of codes `
openssl req -x509 -newkey rsa:4096 -keyout ${ACTIVEMQ_BASE}/key.pem -out ${ACTIVEMQ_BASE}/cert.pem -days 365 -nodes -subj '/O=Eclipse Kapua/C=XX'openssl pkcs8 -topk8 -in ${ACTIVEMQ_BASE}/key.pem -out ${ACTIVEMQ_BASE}/key.pk8 -nocryptrm ${ACTIVEMQ_BASE}/key.pem` 
and this `mkdir -p /opt/jetty /var/opt/jetty/lib/ext /var/opt/jetty/start.d /var/opt/jetty/tls && \`
It has to create my certificate, but it couldn't. what is the problem?

***OpenSSL is installed and my os is ubuntu 20.04

**Comment by lorthirk** [comment]
That part generates the certificate and the private key for JWTs that are used throughout the components of the application, and they have been moved to `/etc/opt/kapua/` in ba19d94820f9e9e42f430517edd681e7d947f8de; though, most probably, this is not what you're looking for.

In order to enable MQTTS connection in the broker you should populate the environment variables that you can find in the [run-broker.sh](https://github.com/eclipse/kapua/blob/develop/assembly/broker/entrypoint/run-broker) entry point.

**Comment by rezahili** [comment]
> That part generates the certificate and the private key for JWTs that are used throughout the components of the application, and they have been moved to `/etc/opt/kapua/` in [ba19d94](https://github.com/eclipse/kapua/commit/ba19d94820f9e9e42f430517edd681e7d947f8de); though, most probably, this is not what you're looking for.
> 
> In order to enable MQTTS connection in the broker you should populate the environment variables that you can find in the [run-broker.sh](https://github.com/eclipse/kapua/blob/develop/assembly/broker/entrypoint/run-broker) entry point.

Do I change something  more than this `KAPUA_DISABLE_SSL:="false"` in the [run-broker.sh](https://github.com/eclipse/kapua/blob/develop/assembly/broker/entrypoint/run-broker) entry point??

**Comment by lorthirk** [comment]
Yes, as you can see from the script you need to have a KeyStore and a TrustStore. How you build those is up to you.

By the way, those variables can be injected from Docker Compose, so you can just export those in the host machine where you launch the Compose. There should be no need to change the script.

**Comment by rezahili** [comment]
> Yes, as you can see from the script you need to have a KeyStore and a TrustStore. How you build those is up to you.
> 
> By the way, those variables can be injected from Docker Compose, so you can just export those in the host machine where you launch the Compose. There should be no need to change the script.


Hi again
I still couldn't make this communication.
I did this `KAPUA_DISABLE_SSL:="false"` 
then According to [ba19d94](https://github.com/eclipse/kapua/commit/ba19d94820f9e9e42f430517edd681e7d947f8de) I created a directory `/etc/opt/kapua/` and then excute these commands:
`openssl req -x509 -newkey rsa:4096 -keyout /etc/opt/kapua/key.pem -out /etc/opt/kapua/cert.pem -days 365 -nodes -subj '/O=Eclipse Kapua/C=XX'`
`openssl pkcs8 -topk8 -in /etc/opt/kapua/key.pem -out /etc/opt/kapua/key.pk8 -nocrypt`
they gave me cf and key in the right directory that I created before.
I didn't change [broker.sh](https://github.com/eclipse/kapua/blob/develop/assembly/broker/entrypoint/run-broker) directories here because they are on the `/etc/opt/Kapua/` by default.
and I copy cr into Kura and change the port to 8883 and I couldn't connect.

Sorry, I'm a novice, and I'm confused about these steps. please tell me step by step and directory by directory how to do it?
and then we could make a document for this part of the communication of Kapua for people like me.Thank u.

**Comment by rezahili** [comment]
> Yes, as you can see from the script you need to have a KeyStore and a TrustStore. How you build those is up to you.
> 
> By the way, those variables can be injected from Docker Compose, so you can just export those in the host machine where you launch the Compose. There should be no need to change the script.

Hi, 
Thank you. I've done what you said (it works but not completely successful:
I mean 
I created a directory `/etc/opt/kapua`
create a certificate and private key and save them.
then I export in entry point and docker-compose files ( in docker-compose I export just certificate and private key).
In the end, I copied the certificate into kura, and now I can see the device is connected, but there is no device in the Devices tab in the console and I couldn't publish. I have these logs and errors:
@lorthirk can you help me?

`18:29:24.573 [ActiveMQ NIO Worker 4] WARN  o.e.k.b.c.p.KapuaSecurityBrokerFilter - User kura (Device1 - tcp://****MYIP***:44154 - conn id 8787155568397833530) is not authorized to write to: topic://VirtualTopic.octo01.kura.Device1.MQTT.DC
broker_1         | 18:29:24.574 [ActiveMQ NIO Worker 4] WARN  o.a.a.b.TransportConnection.Service - Security Error occurred on connection to: tcp://****MYIP***:44154, User kura (Device1 - tcp://****MYIP***:44154 - conn id 8787155568397833530) is not authorized to write to: topic://VirtualTopic.octo01.kura.Device1.MQTT.DC
broker_1         | 18:29:24.574 [ActiveMQ NIO Worker 4] WARN  o.a.a.t.mqtt.MQTTProtocolConverter - Failed to send MQTT Publish:
broker_1         | 18:29:33.381 [ActiveMQ NIO Worker 7] INFO  o.e.k.b.c.p.KapuaSecurityBrokerFilter - User name kura - client id: Device1, connection id: ID:d62dc66d71f9-44505-1623256330016-5:16
broker_1         | 18:29:33.750 [ActiveMQ NIO Worker 7] INFO  o.e.k.s.a.s.AuthenticationServiceShiroImpl - Login for thread '102' - 'ActiveMQ NIO Worker 7' - 'org.apache.shiro.subject.support.DelegatingSubject@59e9c9bc'
broker_1         | 18:29:33.875 [ActiveMQ NIO Worker 0] WARN  o.e.k.b.c.p.KapuaSecurityBrokerFilter - User kura (Device1 - tcp://****MYIP***:44156 - conn id 8787155568397833530) is not authorized to write to: topic://VirtualTopic.octo01.kura.Device1.MQTT.BIRTH
broker_1         | 18:29:33.876 [ActiveMQ NIO Worker 0] WARN  o.a.a.b.TransportConnection.Service - Security Error occurred on connection to: tcp://****MYIP***:44156, User kura (Device1 - tcp://****MYIP***:44156 - conn id 8787155568397833530) is not authorized to write to: topic://VirtualTopic.octo01.kura.Device1.MQTT.BIRTH
broker_1         | 18:29:33.876 [ActiveMQ NIO Worker 0] WARN  o.a.a.t.mqtt.MQTTProtocolConverter - Failed to send MQTT Publish:
broker_1         | 18:29:33.876 [ActiveMQ NIO Worker 0] WARN  o.e.k.b.c.p.KapuaSecurityBrokerFilter - User kura (Device1 - tcp://****MYIP***:44156 - conn id 8787155568397833530) is not authorized to read from: Consumer.2,203,623,492,012,159,476:Device1:AT_LEAST_ONCE.VirtualTopic.octo01.kura.Device1.>
broker_1         | 18:29:33.876 [ActiveMQ NIO Worker 0] WARN  o.a.a.b.TransportConnection.Service - Security Error occurred on connection to: tcp://****MYIP***:44156, User kura (Device1 - tcp://****MYIP***:44156 - conn id 8787155568397833530) is not authorized to read from: Consumer.2,203,623,492,012,159,476:Device1:AT_LEAST_ONCE.VirtualTopic.octo01.kura.Device1.>
broker_1         | 18:29:33.877 [ActiveMQ NIO Worker 0] WARN  o.a.a.t.m.s.AbstractMQTTSubscriptionStrategy - Error subscribing to octo01/kura/Device1/#
broker_1         | java.lang.SecurityException: User kura (Device1 - tcp://****MYIP***:44156 - conn id 8787155568397833530) is not authorized to read from: Consumer.2,203,623,492,012,159,476:Device1:AT_LEAST_ONCE.VirtualTopic.octo01.kura.Device1.>
broker_1         |      at org.eclipse.kapua.broker.core.plugin.KapuaSecurityBrokerFilter.internalAddConsumer(KapuaSecurityBrokerFilter.java:704)
broker_1         |      at org.eclipse.kapua.broker.core.plugin.KapuaSecurityBrokerFilter.addConsumer(KapuaSecurityBrokerFilter.java:664)
broker_1         |      at org.apache.activemq.broker.BrokerFilter.addConsumer(BrokerFilter.java:103)
broker_1         |      at org.apache.activemq.broker.MutableBrokerFilter.addConsumer(MutableBrokerFilter.java:108)
broker_1         |      at org.apache.activemq.broker.TransportConnection.processAddConsumer(TransportConnection.java:706)
broker_1         |      at org.apache.activemq.command.ConsumerInfo.visit(ConsumerInfo.java:351)
broker_1         |      at org.apache.activemq.broker.TransportConnection.service(TransportConnection.java:336)
broker_1         |      at org.apache.activemq.broker.TransportConnection$1.onCommand(TransportConnection.java:200)
broker_1         |      at org.apache.activemq.transport.MutexTransport.onCommand(MutexTransport.java:45)
broker_1         |      at org.apache.activemq.transport.mqtt.MQTTInactivityMonitor.onCommand(MQTTInactivityMonitor.java:162)
broker_1         |      at org.apache.activemq.transport.mqtt.MQTTTransportFilter.sendToActiveMQ(MQTTTransportFilter.java:106)
broker_1         |      at org.apache.activemq.transport.mqtt.MQTTProtocolConverter.sendToActiveMQ(MQTTProtocolConverter.java:181)
broker_1         |      at org.apache.activemq.transport.mqtt.strategy.AbstractMQTTSubscriptionStrategy.doSubscribe(AbstractMQTTSubscriptionStrategy.java:210)
broker_1         |      at org.apache.activemq.transport.mqtt.strategy.MQTTVirtualTopicSubscriptionStrategy.onSubscribe(MQTTVirtualTopicSubscriptionStrategy.java:118)
broker_1         |      at org.apache.activemq.transport.mqtt.strategy.AbstractMQTTSubscriptionStrategy.onSubscribe(AbstractMQTTSubscriptionStrategy.java:118)
broker_1         |      at org.apache.activemq.transport.mqtt.MQTTProtocolConverter.onSubscribe(MQTTProtocolConverter.java:387)
broker_1         |      at org.apache.activemq.transport.mqtt.MQTTProtocolConverter.onMQTTCommand(MQTTProtocolConverter.java:213)
broker_1         |      at org.apache.activemq.transport.mqtt.MQTTTransportFilter.onCommand(MQTTTransportFilter.java:94)
broker_1         |      at org.apache.activemq.transport.TransportSupport.doConsume(TransportSupport.java:83)
broker_1         |      at org.apache.activemq.transport.nio.NIOSSLTransport.doConsume(NIOSSLTransport.java:492)
broker_1         |      at org.apache.activemq.transport.mqtt.MQTTCodec$1.onFrame(MQTTCodec.java:65)
broker_1         |      at org.apache.activemq.transport.mqtt.MQTTCodec.processCommand(MQTTCodec.java:90)
broker_1         |      at org.apache.activemq.transport.mqtt.MQTTCodec.access$400(MQTTCodec.java:26)
broker_1         |      at org.apache.activemq.transport.mqtt.MQTTCodec$4.parse(MQTTCodec.java:213)
broker_1         |      at org.apache.activemq.transport.mqtt.MQTTCodec$3.parse(MQTTCodec.java:179)
broker_1         |      at org.apache.activemq.transport.mqtt.MQTTCodec$2.parse(MQTTCodec.java:138)
broker_1         |      at org.apache.activemq.transport.mqtt.MQTTCodec.parse(MQTTCodec.java:76)
broker_1         |      at org.apache.activemq.transport.mqtt.MQTTNIOSSLTransport.processCommand(MQTTNIOSSLTransport.java:63)
broker_1         |      at org.apache.activemq.transport.nio.NIOSSLTransport.serviceRead(NIOSSLTransport.java:270)
broker_1         |      at org.apache.activemq.transport.nio.NIOSSLTransport$1.onSelect(NIOSSLTransport.java:167)
broker_1         |      at org.apache.activemq.transport.nio.SelectorSelection.onSelect(SelectorSelection.java:98)
broker_1         |      at org.apache.activemq.transport.nio.SelectorWorker$1.run(SelectorWorker.java:118)
broker_1         |      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
broker_1         |      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
broker_1         |      at java.lang.Thread.run(Thread.java:748)
`
