### ISSUE TITLE
Kapua SSO generic provider: RPC service non-application error javax.json.stream.JsonParsingException: Unexpected char 60

### ISSUE THREAD

**Issue by amelroua** [eclipse-kapua/kapua#3350]
Hi,
I want to integrate SSO login to kapua using an external identity server: WSO2 IS. So I configured kapua with WSO2 as follows:

  `     

       image:kapua/kapua-console:${IMAGE_VERSION}
       ports:
        - 8080:8080
        - 8443:8443
    depends_on:
      - broker
      - db
      - es
      - events-broker
    environment:
      - KAPUA_DISABLE_SSL
      - KAPUA_CA
      - KAPUA_CRT
      - KAPUA_KEY
      - KAPUA_KEY_PASSWORD
      - KAPUA_KEYSTORE
      - KAPUA_KEYSTORE_PASSWORD
      - sso.openid.provider=generic                              
      - sso.openid.client.id=xxxxx
      - sso.openid.client.secret=xxxx
      - console.sso.openid.home.uri=http://172.18.0.1:8080
      - sso.openid.generic.jwt.audience.allowed=xxxx
      - sso.openid.generic.jwt.issuer.allowed=https://IS:9443
      - sso.openid.generic.server.endpoint.auth=https://IS:9443/oauth2/authorize 
      -  sso.openid.generic.server.endpoint.token=https://IS:9443/oauth2/token` 

> When I try to access using sso login: I get the following errors from the console logs:
     `    
              
      [qtp913190639-12]     WARNo.e.k.a.c.m.a.s.u.KapuaExceptionHandler      - RPC service non-application error
      javax.json.stream.JsonParsingException: Unexpected char 60 at (line no=19, column no=1, offset=28)
	at org.glassfish.json.JsonTokenizer.unexpectedChar(JsonTokenizer.java:532)
	at org.glassfish.json.JsonTokenizer.nextToken(JsonTokenizer.java:415)
	at org.glassfish.json.JsonParserImpl$NoneContext.getNextEvent(JsonParserImpl.java:222)
	at org.glassfish.json.JsonParserImpl$StateIterator.next(JsonParserImpl.java:172)
	at org.glassfish.json.JsonParserImpl.next(JsonParserImpl.java:149)
	at org.glassfish.json.JsonReaderImpl.readObject(JsonReaderImpl.java:101)
	at org.eclipse.kapua.plugin.sso.openid.provider.OpenIDUtils.getConfigUri(OpenIDUtils.java:74)
	at org.eclipse.kapua.plugin.sso.openid.provider.generic.GenericOpenIDService.getAuthUri(GenericOpenIDService.java:52)
`

> Note: this error occurs when I solved a certificate issue and I added wso2 certificate to java keystore

**Comment by lorthirk** [comment]
It seems that the request to the `.well-known/openid-configuration` does not contain a valid JSON. Can you reach that in your identity server?

Also, set `LOGBACK_LOG_LEVEL` to `DEBUG` in the Docker Compose. You should get more info about the request, so you can check that the URL is correct.

**Comment by amelroua** [comment]
Thanks for your reply. I can connect to the identity server from the console. when I execute the curl command from the console container to .well-known/openid-configuration, I get a json response:

curl -v -k --user admin:admin https://IS:9443/oauth2/oidcdiscovery/.well-known/openid-configuration 

     `{"request_parameter_supported":true,"claims_parameter_supported":true,"introspection_endpoint":"https://is.sodira.com:9443/oauth2/introspect","Response_modes_supported":["query","fragment","form_post"],"scopes_supported":["address","phone","openid","profile","email"],"check_session_iframe":"https://is.sodira.com:9443/oidc/checksession","backchannel_logout_supported":true,"issuer":"https://localhost:9443/oauth2/token","authorization_endpoint":"https://is.sodira.com:9443/oauth2/authorize","introspection_endpoint_auth_methods_supported":["client_secret_basic","client_secret_post"] }`

While debugging I found that the used URL is not the right one : https://IS:9443/.well-known/openid-configuration

I added the right URL in the docker compose :
     
 `-sso.openid.conf.wellknown.path=https://IS:9443/oauth2/oidcdiscovery/.well-known/openid-configuration`

But when debbugging again I found that the URL that I added is not considered and I get always the URL: https://IS:9443/.well-known/openid-configuration

**Comment by lorthirk** [comment]
So you should set `sso.openid.conf.path` to `/oauth2/oidcdiscovery/.well-known/openid-configuration`.

https://github.com/eclipse/kapua/blob/e990e3a7ee439b874c3d5442b680dd32f128e5f8/docs/developer-guide/en/sso.md#enabling-single-sign-on

**Comment by amelroua** [comment]
Thanks so so much my problem is solved :)

**Comment by lorthirk** [comment]
Glad to hear! Closing.

**Comment by amelroua** [comment]
I'm sorry I got the same error of reading /.well-known/openid-configuration but in the kapua.service.authentication.shiro:

      `[qtp913190639-17] DEBUG o.e.k.s.a.shiro.KapuaAuthenticator - Realm [org.eclipse.kapua.service.authentication.shiro.realm.UserPassAuthenticatingRealm@c862f61] does not support token org.eclipse.kapua.service.authentication.shiro.JwtCredentialsImpl@6c58ff9.  Skipping realm. 
    10:05:28.250 [qtp913190639-17] ERROR o.e.k.p.s.o.provider.OpenIDUtils - IOException occurred while reading the well-known resource: Connection refused (Connection refused)`

This connection refused issue occurs because I found that the well-known path taken is: `https://localhost:9443/oauth2/token/oauth2/oidcdiscovery/.well-known/openid-configuration`

instead of https://IS:9443/oauth2/token/oauth2/oidcdiscovery/.well-known/openid-configuration

     `[qtp913190639-17] DEBUG o.e.k.p.s.o.provider.OpenIDUtils - =================== OpenID Provider Configuration Information ===================
     10:05:28.266 [qtp913190639-17] DEBUG o.e.k.p.s.o.provider.OpenIDUtils - |  Requested property: jwks_uri
     10:05:28.266 [qtp913190639-17] DEBUG o.e.k.p.s.o.provider.OpenIDUtils - |  From well-known path: https://localhost:9443/oauth2/token/oauth2/oidcdiscovery/.well-known/openid-configuration
    10:05:28.267 [qtp913190639-17] DEBUG o.e.k.p.s.o.provider.OpenIDUtils - ==========================================
    10:05:28.291 [qtp913190639-17] DEBUG o.e.k.s.a.shiro.KapuaAuthenticator - Realm [org.eclipse.kapua.service.authentication.shiro.realm.JwtAuthenticatingRealm@31e5ef29] threw an exception during a multi-realm authentication attempt:
    org.apache.shiro.ShiroException: Failed to parse JWT`
As I mentioned in my configuration I'm using IS domain name and not localhost.

**Comment by lorthirk** [comment]
As you can read in the README posted above, the value of `sso.openid.conf.path` is appended to the value of `sso.openid.generic.jwt.issuer.allowed` in order to build the full URI. So if you get `https://localhost:9443/oauth2/token/oauth2/oidcdiscovery/.well-known/openid-configuration` as a full URI, it means that `sso.openid.generic.jwt.issuer.allowed` is set to `https://localhost:9443`. You should change this to `https://IS:9443`.

**Comment by amelroua** [comment]
Thanks for your reply but as you can see in my first post of my configuration, I set up `sso.openid.generic.jwt.issuer.allowed=https://IS:9443`

**Comment by lorthirk** [comment]
According to the current implementation:

https://github.com/eclipse/kapua/blob/dd481c52c43202d55fe8f8c3aafdbec933230cb0/plug-ins/sso/openid-connect/provider/src/main/java/org/eclipse/kapua/plugin/sso/openid/provider/OpenIDUtils.java#L125-L137

I can confirm that the well known path is appended to the issuer. I'm afraid that the only way to investigate is here is with a debugging session to inspect the actual value.
