### ISSUE TITLE
Step properties field having different names

### ISSUE THREAD

**Issue by mmartinez57** [eclipse-kapua/kapua#3580]
**Describe the bug**
The step properties' field is called different depending on what request are you using. 

- If you are using a POST request, the properties' field in your request's body has to be called "jobStepProperties".
- If you are using a PUT request, the properties' field in your request's body has to be called "stepProperties".
- If you use a GET request, the properties' field in your response's body is called "stepProperties".

**Expected behavior**
The field having the same name in all the requests and responses.

**Screenshots**
Screenshots taken from the official API documentation: https://www.eclipse.org/kapua/docs/api/index.html?version=1.5.0#/Job%20-%20Step
POST request's body:
![Captura de pantalla de 2022-07-08 09-56-57](https://user-images.githubusercontent.com/91335442/177945389-f167d836-f5d2-4840-934a-65249ec23353.png)
PUT request's body:
![Captura de pantalla de 2022-07-08 09-58-37](https://user-images.githubusercontent.com/91335442/177945653-7419b764-f3b2-42d7-9b38-50239d921cd5.png)
GET response's body:
![Captura de pantalla de 2022-07-08 09-57-40](https://user-images.githubusercontent.com/91335442/177945504-9e1e514d-4158-4777-8591-1629a54ee2ef.png)

**Version of Kapua**
1.5.X

**Main component affected**
[ ] Console (in case of console please report info on which browser you encountered the problem)
[X] REST API
[ ] Message Broker
[ ] - Others

**Comment by Coduz** [comment]
Hi @mmgspr 

Thanks for submitting the issue! 

@MDeLuise made a PR to fix this issue and make the models uniform between different entities.

Changes made still support old way to define the `stepProperties` so no immediate change is required upon version upgrade. 

Fix will be available in:

- 2.0.0
- 1.7.0
- 16.8
- 1.5.8
