### ISSUE TITLE
Kapua console at 104.196.28.15:443 need updating

### ISSUE THREAD

**Issue by eclipsewebmaster** [eclipse-kapua/kapua#3664]
There is a console at 104.196.28.15:443. This console is reported to allow insecure protocol: TLSv1.0 and llows insecure protocol: TLSv1.1; Missing intermediate certificates or untrusted root anchor

These two TLS protocols must be disabled, with minimum TLSv1.2 acceptable.

The EF is required to adhere to strict security protocols and practices, and as this service operates under our domain name, it must be updated.

Thanks!

**Comment by eclipsewebmaster** [comment]
Security protocols and practices require prompt attention to this issue. Can someone on the project comment?  Or is the console not used anymore?

**Comment by eclipsewebmaster** [comment]
I have stopped the virtual machine until further notice.

**Comment by Coduz** [comment]
Hi @eclipsewebmaster ,

sorry for the late response.

For that deployment we do not have memories and this is likely why it was never updated. 
Can you please give us info about how to manage and where is deployed this Kapua? 

Regards, 

Alberto

**Comment by Coduz** [comment]
Closing this due to no answer. 

@eclipsewebmaster feel free to re-open this if needed. 

Regards, 

_Alberto_
