### ISSUE TITLE
Unable to run Kapua containers in local

### ISSUE THREAD

**Issue by NagaRajeshK** [eclipse-kapua/kapua#3773]
Hi Team,
I am not able to run Kapua setup in my local. Looks like Kapua images are not available. How can I pull the images? Where are they hosted? I am not able to build the code in my local as well, Please check second screenshot. .Could you please help?

Error:
"Error response from daemon: pull access denied for kapua/kapua-consumer-lifecycle, repository does not exist or may require 'docker login': denied: requested access to the resource is denied"
![image](https://github.com/eclipse/kapua/assets/5278392/40dcedab-d32f-4757-b692-c9cc6747f96e)

When I am trying to build the code:
![image](https://github.com/eclipse/kapua/assets/5278392/594e6914-98fc-4104-a7f5-d0a5dd10bd58)

**Comment by Agnul97** [comment]
Hi, 
if you want to deploy kapua pulling those images, checkout to one release branch (for example, release 1.6.x or 1.7.x) and try the same method of deployment, missing images should not be a problem anymore.
If you want to contribute and build/deploy the development branch, let me know and I'll provide more help

**Comment by Agnul97** [comment]
https://github.com/eclipse/kapua/pull/3777

**Comment by NagaRajeshK** [comment]
Hi @Agnul97  
Thanks for the help. I have download the code of the 1.6.7 tag. I am able to run the docker containers.

Thanks,
Rajesh.

**Comment by Agnul97** [comment]
@NagaRajeshK let me know if you have problems with the deployment because with my mac M2 I had problems with the event-broker deployment
