### ISSUE TITLE
Simulating a Kura device, connection established, but the device itself isn't connected

### ISSUE THREAD

**Issue by Zare22** [eclipse-kapua/kapua#4151]
Hello. I'm developing my finals project using Kapua. On one side I want to emulate Kura devices. The issue I'm currently facing, but can't seem to find an answer to, is as the title states. I can establish connection and I am publishing payloads, I can also subscribe to topics on the "other" side, but what is weird to me is that although the connection is established, the device itself is never connected in console. Is it even possible to simulate a full device and if so could you point me to documentation part that explains that if I have missed it. Thanks!

Edit: images showing connections weren't really clear

![{F64965D0-8359-4FE7-8141-E85721CC9D1E}](https://github.com/user-attachments/assets/6213f267-a143-4c92-9e26-544ff90ca336)
![{F4757216-FD4C-4F38-929C-22FD17CAF710}](https://github.com/user-attachments/assets/ec251730-45d2-4878-abb0-85ffaf0783bf)
![{DEC90F48-7762-46D4-B8BA-E3A67031C98E}](https://github.com/user-attachments/assets/5946636a-5ece-47b6-a22a-11f433e12095)
![{179B57FB-17B0-4DFF-9442-81A380C57E41}](https://github.com/user-attachments/assets/f5c4717b-89b6-48eb-9a46-9d14287d36d8)
![{0F755FBA-0060-44EC-8421-333CB8B3F384}](https://github.com/user-attachments/assets/cf6ad626-fda6-4098-8ce7-d328fafd3765)

**Comment by Agnul97** [comment]
The fact is that in order to connect to the console as a device it has to send a so called "birth message" but there is a lack of documentation for this as I see in the kura documentation. The kura device, for example, sends this birth

**Comment by Zare22** [comment]
Thanks for your reply!

I can't seem to find the structure for it though. There's no .proto file for it like there is one for KuraPayload

**Comment by Zare22** [comment]
Managed to publish Kura Birth Message by debugging Kapua gateway client from ctron and inspecting it!

For anyone searching for this in the future. Birth message should be published to a topic right after you establish your connection with client of choice.

Topic structure for birth message:
`$EDC/<accountName>/<clientId>/MQTT/BIRTH`

It will be valid even if $EDC is not included, but then it goes to data, this register it as event. Not sure, but from the looks of it in the console that's how I'm interpreting it.
Payload can actually be empty. But it can consist of KuraMetrics that are part of device properties.

![{F927C565-8A07-48C3-A196-ADEDCCAFEE51}](https://github.com/user-attachments/assets/7fd98653-206e-4747-8b31-7272a270da6f)

![{AED1FFB7-2FBA-4838-965D-5322AB002B10}](https://github.com/user-attachments/assets/d15d8ab9-9f04-42e0-be6b-7a0c0b56bea9)

**Comment by Agnul97** [comment]
@Zare22 I'll add your findings inside the official documentation of the project, thanks
